# -*- coding: cp1252 -*-
en_EN = {
    "title":"Abyss points sharer - Aion",
    "lang":"English",
    "i_i":"Lesser ancient icon",
    "i":"Ancient icon",
    "i_s":"Greater ancient icon",
    "i_m":"Major ancient icon",
    "s_i":"Lesser ancient seal",
    "s":"Ancient seal",
    "s_s":"Greater ancient seal",
    "s_m":"Major ancient seal",
    "t_i":"Lesser ancient goblet",
    "t":"Ancient goblet",
    "t_s":"Greater ancient goblet",
    "t_m":"Major ancient goblet",
    "c_i":"Lesser ancient crown",
    "c":"Ancient crown",
    "c_s":"Greater ancient crown",
    "c_m":"Major ancient crown",
    "first":"st",
    "second":"nd",
    "rd":"rd",
    "statment1":"rolled the dice and got",
    "statment2":"Gamefile directory :",
    "statment3":"Language :",
    "statment4":"Please select the Aion folder where you can find aion.bin",
    "config":"Settings"
    }

fr_FR = {
    "title":"Partageur de points abyssaux - Aion",
    "lang":"Français",
    "i_i":"Icône antique inférieure",
    "i":"Icône antique",
    "i_s":"Icône antique supérieure",
    "i_m":"Icône antique majeure",
    "s_i":"Sceau antique inférieur",
    "s":"Sceau antique",
    "s_s":"Sceau antique supérieur",
    "s_m":"Sceau antique majeur",
    "t_i":"Timbale antique inférieure",
    "t":"Timbale antique",
    "t_s":"Timbale antique supérieure",
    "t_m":"Timbale antique majeure",
    "c_i":"Couronne antique inférieure",
    "c":"Couronne antique",
    "c_s":"Couronne antique supérieure",
    "c_m":"Couronne antique majeure",
    "first":"er",
    "second":"ème",
    "rd":"ème",
    "statment1":"lancé les dés et obtenu",
    "statment2":"Répertoire du jeu :",
    "statment3":"Langue :",
    "statment4":"Veuillez sélectionner le répértoire d'Aion où se trouve aion.bin",
    "config":"Paramètres"
    }
